name: Deploy
on:
  push:
    branches:
      - master


jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "16"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
         sudo npx ncc build index.ts      
         zip -j deploy.zip ./dist/*
         aws lambda update-function-code --function-name=rndk-auth --zip-file=fileb://deploy.zip
