name: Deploy
on:
  push:
    branches:
      -master


jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: '18'
      - name: npm install
        env:
          CI: true
        run: | 
          npm ci
